
#ifndef __HE_ROUTE_APP_HEADER__
#define __HE_ROUTE_APP_HEADER__

#define IN
#define OUT

typedef CHAR RETCODE;

typedef enum HERT_STATUS
{
    HERT_UNREGISTER = 0x0,
    HERT_REGISTERED,
}HERT_STATUS;

#define MAX_BUFF_SIZE  2048

typedef enum RETCODE_ERR
{
    RETCODE_SUCCESS = 0x0,
    RETCODE_INVALID_PARAM,
    RETCODE_INVALID_MSGDATA,
    RETCODE_NO_MEMORY,
    RETCODE_NO_RESOURCE,
    RETCODE_INTERNEAL_ERROR,
    RETCODE_TCPSOCKET_ERROR,
    RETCODE_UNREACHABLE_ERROR,
    RETCODE_NOIMPORTMENT_ERROR
}RETCODE_ERR;


#endif /* __HE_ROUTE_APP_HEADER__ */

